# Generated by Django 5.2.11 on 2026-03-08 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='passenger',
            name='email',
            field=models.EmailField(default='none@example.com', max_length=254),
            preserve_default=False,
        ),
    ]
