# Generated by Django 5.2.11 on 2026-03-26 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0002_passenger_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='airport',
            name='details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_code',
            field=models.CharField(editable=False, max_length=8, unique=True),
        ),
    ]
